Visitor can Register for an account
CraftAcademy/classy_news_client pull request #8
Opened 2019-10-28 09:11 UTC by DavveDavve

[PT Link](https://www.pivotaltracker.com/story/show/169285628)

## PR Content
- Signup Form Component
- Redux Token Auth implementation for user registration
- State/Event Handlers
- Styling

## What have we learned
- How to implement redux token auth
- How to use debuggers and logger
- The use of props

## Screenshots

2019-10-28 13:39 UTC, beccaburns approved these changes

2019-10-28 13:40 UTC, lucamarial approved these changes

2019-10-28 14:42 UTC, yasmineezequiel approved these changes

2019-10-29 06:52 UTC, faraznaeem requested changes

2019-10-29 06:52 UTC, faraznaeem commented on cypress/integration/userCanSignUp.spec.js
> +  })
You are missing a sad path for this feature

2019-10-29 13:51 UTC, lucamarial approved these changes

2019-10-29 16:08 UTC, DIzosimov commented on cypress/integration/userCanSignUp.spec.js
> +  })
fixed :)

2019-10-30 15:20 UTC, merged